"""add id in the index

Revision ID: 2a6c72a404bc
Revises: 6f4fc55c2b3d
Create Date: 2026-05-15 12:57:15.215298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6c72a404bc'
down_revision: Union[str, Sequence[str], None] = '6f4fc55c2b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_created_at'), table_name='messages')
    op.create_index('ix_messages_conversation_created_at_id', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.alter_column('notification_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_messages_conversation_created_at_id', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_created_at'), 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
