"""add device_id in notification token

Revision ID: 42a0d4b941a5
Revises: 2a6c72a404bc
Create Date: 2026-05-15 13:16:29.421015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a0d4b941a5'
down_revision: Union[str, Sequence[str], None] = '2a6c72a404bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_tokens', sa.Column('device_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'notification_tokens', ['user_id', 'device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_tokens', type_='unique')
    op.drop_column('notification_tokens', 'device_id')
    # ### end Alembic commands ###
