"""add notification tokens and messages cusor index

Revision ID: 6f4fc55c2b3d
Revises: b7c3d9e4f1a2
Create Date: 2026-05-15 12:00:38.133590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4fc55c2b3d'
down_revision: Union[str, Sequence[str], None] = 'b7c3d9e4f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_conversation_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created_at', table_name='messages')
    # ### end Alembic commands ###
