"""Add Conversation and Message Model

Revision ID: ba8d14c6b2c1
Revises: f0f0fb6a7986
Create Date: 2026-01-10 23:28:45.825115

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ba8d14c6b2c1"
down_revision: str | Sequence[str] | None = "f0f0fb6a7986"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
